spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/test
    driverClassName: org.h2.Driver
    username: sa
    password:

  h2.console:
    enaled: true
    path: /h2-console

  jpa:
#    database: h2
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create
      use.sql_format: true
    show-sql: true
    properties:
      hibernate:
        format_sql: true


  output.ansi.enabled: always  # terminal color
